Update README with initial information
cisagov/cisagov pull request #2
Opened 2021-02-24 17:00 UTC by hillaryj

#  #

## 🗣 Description ##

Replaces skeleton information with useful information.

## 💭 Motivation and context ##

## 🧪 Testing ##

Documentation only, no testing required other than linting.

## ✅ Checklist ##

* [ ] This PR has an informative and human-readable title.
* [ ] Changes are limited to a single goal - _eschew scope creep!_
* [ ] All relevant type-of-change labels have been added.
* [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [ ] All new and existing tests pass.

2021-02-24 17:45 UTC, jsf9k requested changes
I made some suggestions, one of which is a fix for the failing pre-commit linters.

2021-02-24 17:45 UTC, jsf9k commented on README.md
> +environment, and other information
```suggestion
We have a [cisagov development-guide](www.github.com/cisagov/development-guide)
repository, which contains coding standards, steps for setting up a development
environment, and other information.
```

2021-02-24 17:45 UTC, jsf9k commented on README.md
> +Welcome to `cisagov`, the GitHub organization for CISA.
```suggestion
Welcome to `cisagov`, the GitHub organization for the Cybersecurity and Infrastructure Security Agency (CISA).
```

2021-02-24 17:45 UTC, jsf9k commented on README.md
> +  - Content guides & best practices
This should fix the linting errors:
```suggestion
- How do I make an account?
- How do I get access?
- How do I make a repository?
- Content guides & best practices
```

2021-02-24 21:09 UTC, dav3r approved these changes
Approved, assuming you make the changes requested by @jsf9k. 👍 👍

2021-02-25 15:42 UTC, jsf9k approved these changes

2021-02-25 18:46 UTC, mcdonnnj approved these changes
📜

2021-02-26 15:57 UTC, merged